# Generated by Django 5.2.17 on 2026-09-23 01:36

import django.core.validators
import django.db.models.deletion
import tastings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=70)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(15)],
                    ),
                ),
                (
                    "price_per_guest",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Maximum guests per time slot.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_party_size",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Largest group one booking can hold.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["winery", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Defaults to the experience capacity.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Closed slots take no new bookings."
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="tastings.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=tastings.models.new_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("guest_name", models.CharField(max_length=120)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                (
                    "party_size",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Allergies, celebrations, accessibility needs.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="tastings.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["slot__start", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Winery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=70, unique=True)),
                (
                    "region",
                    models.CharField(
                        help_text="e.g. Napa Valley, Willamette Valley", max_length=80
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Booking notifications are sent here.", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished wineries are hidden from guests.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wineries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "wineries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="winery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="tastings.winery",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("experience", "start"), name="unique_slot_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.UniqueConstraint(
                fields=("winery", "slug"), name="unique_experience_slug"
            ),
        ),
    ]
